### ISSUE TITLE
Use Trash icon

### ISSUE THREAD

**Issue by YamShadow** [dcasia/clickable-table-row#1]
Hello, 

You can not use the trash icon after installing your module.

When we click on it, we are redirected to the detailed view and not to the modal allowing the item to be deleted.

**Comment by milewski** [comment]
@YamShadow Hi, can you double-check if you are using the latest version and your cache is clean? I have it installed on some of my projects and I don't face this issue

![image](https://user-images.githubusercontent.com/2874967/69436225-e6a60580-0d7b-11ea-9edd-cb7fd6fb7b1f.png)

**Comment by YamShadow** [comment]
Arf, sorry

Attention to the cache level of view ...

Thank you for your prompt response !
