### ISSUE TITLE
Conflicts with Actions on table rows

### ISSUE THREAD

**Issue by MikeCraig418** [dcasia/clickable-table-row#12]
Clicking on the Action Dropdown attempts to load the view via this script:

![image](https://user-images.githubusercontent.com/23151962/87577884-70e30700-c688-11ea-999f-90a97e17f6b1.png)

Expected behavior:

* Don't load the resource. 
* Show the action dropdown

**Comment by vesper8** [comment]
How do you get an inline action dropdown to work? Is that a plugin?

**Comment by milewski** [comment]
@vesper8 on the action resource itself do something like this:

```php
public function actions() {
 return [
    (new YourAction)->showOnTableRow() 
 ];
}

**Comment by tips-hq** [comment]
Is there a fix for this? It is still occurring for me Laravel Nova v3.2.

When I click inline action. It takes me to resource detail
