### ISSUE TITLE
Proposal: set the details of the record to be displayed in the popup below the row when clicked

### ISSUE THREAD

**Issue by oleksandr-roskovynskyi** [dcasia/clickable-table-row#3]
It is also necessary to foresee collapsing when clicking again on the same line, now, I am engaged in the development of this functionality. I will be very grateful for your help!
For example:
<img width="1276" alt="dashboard detail nova example" src="https://user-images.githubusercontent.com/57599426/72664963-65ca5980-3a0c-11ea-8971-665e3cdf8341.png">
This will improve the adaptability of the table to view the details of the record without losing sight of the current row.

Also a big thank you for developing this package!!!!

**Comment by milewski** [comment]
I think this would be quite of a challenge to create, first you would need to override the default nova table component with a custom one to be able to add custom functionality like collapsing/expanding, and then you would need to find a way to retrieve all these extra fields to populate the table when it's expanded, I have no clue how this could be done, if you have some ideas share it let's discuss

**Comment by oleksandr-roskovynskyi** [comment]
I will try to insert to a component row deployment/collapse component (nova/resources/js/views/Detail.vue) or, as a last resort, create a popup window with record details

**Comment by oleksandr-roskovynskyi** [comment]
There was an idea in a component to implement a hidden line with all details (div class = "hidden"> [Detail.vue] </div) at once, and at click to show/hide, I will try to implement ...
How is your idea?

**Comment by milewski** [comment]
I think something like this: 

```php
Number::make('Quantity'),
Number::make('Price'),
Number::make('Sold Price'),

HiddenDetailField::make(function (){
   return [
       Text::make('A'),
       Text::make('B'),
       Text::make('C'),
   ];
}),
```

The`HiddenDetailField` renders on index view as an arrow or something that user can click

this way you will have exactly the fields you want to show within the expandable panel
