### ISSUE TITLE
JS error in Safari: TypeError: undefined is not an object (evaluating 't.path.some')

### ISSUE THREAD

**Issue by gergoo** [dcasia/clickable-table-row#4]
Hi!

In Safari I get this error: TypeError: undefined is not an object (evaluating 't.path.some'), clickable-table-row:35.

How can I fix it?

Thanks!

![safari-issue](https://user-images.githubusercontent.com/2934385/73926842-96e1cf80-48d0-11ea-99e1-270afbfffdc2.png)

**Comment by milewski** [comment]
I have noticed this also happening on firefox
