### ISSUE TITLE
New to Nova.... 

### ISSUE THREAD

**Issue by mikeerickson** [dcasia/clickable-table-row#6]
I am sorry to sound insensitive, since I am new to Nova (just getting started) when would this be necessary / beneficial?  When one clicks on a row, what action(s) would I be able to perform?

**Comment by milewski** [comment]
What this package does is exactly what it advertises, you click on the row and open the resource, natively without this package you need to click on the "eye" icon to view the resource, it's fine if you are a developer and only you will be using the dashboard, however, most of the non-tech users feel it is unintuitive to have to click on that eye... there are some users that even thinks it's a bug as they click on the row and nothing happens... so essentially what this package does is improve the UX a bit...

**Comment by mikeerickson** [comment]
Hmm, yes I can see your position here. I am thinking what would be more intuitive would be a doubleclick as you would in Finder / File Manager.  Is the @click ignored if clicking the checkbox icon

**Comment by milewski** [comment]
Yes the click is ignore if clicking in some types of elements like SVG, button, input etc. Perhaps you are using a custom field that display a button on the index view so these kind of elements would be automatically ignored by this package as long as they use one or these ignored elements I mentioned

**Comment by mikeerickson** [comment]
I can now see why this would be useful, curious if it could be extended / enhanced to use doubleClick as opposed to click.  As stated, I am still new to Nova so I have not hit some of the “pain points” yet so I am merely inquiring

**Comment by milewski** [comment]
Yes there was an issue here on this repo someone asking for this option before.. it's possible but we would need to introduce a config file to setup the behavior it would take.

But personally I think double click feels wierd on the web.. Because if you hover the row your cursor changes to a pointer, which suggest you can click on that element, however if you just single click.. Nothing would happen..
